CREATE DATABASE  IF NOT EXISTS chatdata;
use chatdata;
CREATE TABLE IF NOT EXISTS `chats`(
	`id` int(6) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`info` mediumtext NOT NULL,
	`user` VARCHAR(100) NOT NULL
)CHARSET=UTF8;
